import { readLocalState, writeLocalState } from '@/services/mobileDatabase'

const today = () => new Date().toISOString().slice(0, 10)
const month = (date = today()) => date.slice(0, 7)
const defaults = [
  ['Moradia', '#7c5cff'], ['Alimentação', '#f59e0b'], ['Transporte', '#38bdf8'], ['Lazer', '#ec4899'],
  ['Saúde', '#22c55e'], ['Educação', '#a78bfa'], ['Outros', '#64748b'],
]

function initialState() {
  return {
    nextId: 8,
    categories: defaults.map(([name, color], index) => ({ id: index + 1, name, color, budget_limit: null, is_archived: false })),
    transactions: [], goals: [], deposits: [], receivables: [], receivablePayments: [], recurring: [], occurrences: [],
    cards: [], invoices: [], purchases: [], invoicePayments: [], clients: [], products: [], plans: [], subscriptions: [], saasInvoices: [], saasPayments: [],
  }
}

async function state() {
  const saved = await readLocalState()
  if (saved) return saved
  const created = initialState()
  await writeLocalState(created)
  return created
}

async function change(operation) {
  const data = await state()
  const result = operation(data)
  await writeLocalState(data)
  return result
}

function id(data) { return data.nextId++ }
function copy(value) { return structuredClone(value) }
function required(value, message) { if (value === undefined || value === null || value === '') throw new Error(message); return value }
function positive(value, message = 'Informe um valor maior que zero.') { const result = Number(value); if (!(result > 0)) throw new Error(message); return result }
function find(items, itemId, message = 'Recurso não encontrado.') { const item = items.find((entry) => entry.id === Number(itemId)); if (!item) throw new Error(message); return item }
function category(data, categoryId) { return find(data.categories, categoryId, 'Categoria não encontrada.') }
function range(period) { return [period ? `${period}-01` : '', period ? `${period}-31` : ''] }
function transactionView(data, item) { const itemCategory = item.category_id ? data.categories.find((entry) => entry.id === item.category_id) : null; return { ...copy(item), category_name: itemCategory?.name || null, category_color: itemCategory?.color || null } }
function goalView(data, item) { const saved = data.deposits.filter((entry) => entry.goal_id === item.id).reduce((sum, entry) => sum + entry.amount, 0); return { ...copy(item), saved_amount: saved, progress: Math.min(100, Math.round(saved / item.target_amount * 100)), is_completed: saved >= item.target_amount } }
function receivableView(data, item) { const received = data.receivablePayments.filter((entry) => entry.receivable_id === item.id).reduce((sum, entry) => sum + entry.amount, 0); return { ...copy(item), received_amount: received, pending_amount: Math.max(0, item.total_amount - received), progress: Math.min(100, Math.round(received / item.total_amount * 100)) } }
function createTransaction(data, payload) {
  const type = required(payload.type, 'Informe o tipo da transação.')
  if (!['income', 'expense'].includes(type)) throw new Error('Tipo de transação inválido.')
  if (type === 'expense') category(data, required(payload.category_id, 'Informe uma categoria.'))
  const item = { id: id(data), date: required(payload.date, 'Informe a data.'), type, amount: positive(payload.amount), category_id: type === 'expense' ? Number(payload.category_id) : null, description: payload.description || null, created_at: new Date().toISOString() }
  data.transactions.push(item)
  return transactionView(data, item)
}
function occurrenceDates(item, until = 12) {
  const output = []; const start = new Date(`${item.start_date}T12:00:00`); const end = item.end_date ? new Date(`${item.end_date}T12:00:00`) : null
  for (let index = 0; index < until; index += 1) {
    const date = new Date(start)
    if (item.frequency === 'daily') date.setDate(start.getDate() + index * item.interval)
    if (item.frequency === 'weekly') date.setDate(start.getDate() + index * item.interval * 7)
    if (item.frequency === 'monthly') date.setMonth(start.getMonth() + index * item.interval)
    if (item.frequency === 'yearly') date.setFullYear(start.getFullYear() + index * item.interval)
    if (end && date > end) break
    output.push(date.toISOString().slice(0, 10))
  }
  return output
}

export const localApi = {
  async categories() { const data = await state(); return copy(data.categories.filter((item) => !item.is_archived)) },
  async createCategory(payload) { return change((data) => { const name = required(payload.name?.trim(), 'Informe o nome da categoria.'); if (data.categories.some((item) => item.name.toLowerCase() === name.toLowerCase())) throw new Error('Já existe uma categoria com este nome.'); const item = { id: id(data), name, color: payload.color || '#64748b', budget_limit: null, is_archived: false }; data.categories.push(item); return copy(item) }) },
  async updateCategory(itemId, payload) { return change((data) => { const item = category(data, itemId); const name = required(payload.name?.trim(), 'Informe o nome da categoria.'); if (data.categories.some((entry) => entry.id !== item.id && entry.name.toLowerCase() === name.toLowerCase())) throw new Error('Já existe uma categoria com este nome.'); Object.assign(item, { name, color: payload.color || item.color }); return copy(item) }) },
  async setBudget(itemId, budgetLimit) { return change((data) => { const item = category(data, itemId); item.budget_limit = budgetLimit === null || budgetLimit === '' ? null : positive(budgetLimit); return copy(item) }) },
  async deleteCategory(itemId) { return change((data) => { const item = category(data, itemId); if (data.transactions.some((entry) => entry.category_id === item.id) || data.purchases.some((entry) => entry.category_id === item.id)) { item.is_archived = true; return { archived: true } } data.categories = data.categories.filter((entry) => entry.id !== item.id); return { archived: false } }) },
  async transactions(params = {}) { const data = await state(); return data.transactions.filter((item) => (!params.type || item.type === params.type) && (!params.category_id || item.category_id === Number(params.category_id)) && (!params.date_from || item.date >= params.date_from) && (!params.date_to || item.date <= params.date_to)).sort((a, b) => b.date.localeCompare(a.date) || b.id - a.id).map((item) => transactionView(data, item)) },
  async createTransaction(payload) { return change((data) => createTransaction(data, payload)) },
  async updateTransaction(itemId, payload) { return change((data) => { const item = find(data.transactions, itemId, 'Transação não encontrada.'); const type = required(payload.type, 'Informe o tipo da transação.'); if (type === 'expense') category(data, required(payload.category_id, 'Informe uma categoria.')); Object.assign(item, { date: required(payload.date, 'Informe a data.'), type, amount: positive(payload.amount), category_id: type === 'expense' ? Number(payload.category_id) : null, description: payload.description || null }); return transactionView(data, item) }) },
  async deleteTransaction(itemId) { return change((data) => { data.transactions = data.transactions.filter((item) => item.id !== Number(itemId)); return null }) },
  async dashboard(period) { const data = await state(); const selected = period || month(); const items = data.transactions.filter((item) => month(item.date) === selected); const income = items.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amount, 0); const expense = items.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0); const byCategory = data.categories.map((item) => ({ name: item.name, color: item.color, amount: items.filter((entry) => entry.type === 'expense' && entry.category_id === item.id).reduce((sum, entry) => sum + entry.amount, 0) })).filter((item) => item.amount); const balance = data.transactions.reduce((sum, item) => sum + (item.type === 'income' ? item.amount : -item.amount), 0) - data.deposits.reduce((sum, item) => sum + item.amount, 0); return { balance, income, expense, by_category: byCategory, monthly_evolution: [] } },
  async budgets(period) { const data = await state(); const selected = period || month(); return data.categories.filter((item) => !item.is_archived && item.budget_limit !== null).map((item) => { const spent = data.transactions.filter((entry) => entry.type === 'expense' && entry.category_id === item.id && month(entry.date) === selected).reduce((sum, entry) => sum + entry.amount, 0); return { ...copy(item), spent, percentage: item.budget_limit ? Math.round(spent / item.budget_limit * 100) : 0 } }) },
  async goals() { const data = await state(); return data.goals.map((item) => goalView(data, item)) },
  async goal(itemId) { const data = await state(); const item = find(data.goals, itemId, 'Meta não encontrada.'); return { ...goalView(data, item), deposits: copy(data.deposits.filter((entry) => entry.goal_id === item.id).sort((a, b) => b.id - a.id)) } },
  async createGoal(payload) { return change((data) => { const item = { id: id(data), name: required(payload.name?.trim(), 'Informe o nome da meta.'), target_amount: positive(payload.target_amount), deadline: payload.deadline || null, description: payload.description || null, created_at: new Date().toISOString() }; data.goals.push(item); return goalView(data, item) }) },
  async updateGoal(itemId, payload) { return change((data) => { const item = find(data.goals, itemId, 'Meta não encontrada.'); Object.assign(item, { name: required(payload.name?.trim(), 'Informe o nome da meta.'), target_amount: positive(payload.target_amount), deadline: payload.deadline || null, description: payload.description || null }); return goalView(data, item) }) },
  async deleteGoal(itemId) { return change((data) => { data.goals = data.goals.filter((item) => item.id !== Number(itemId)); data.deposits = data.deposits.filter((item) => item.goal_id !== Number(itemId)); return null }) },
  async addDeposit(goalId, payload) { return change((data) => { const goal = find(data.goals, goalId, 'Meta não encontrada.'); const item = { id: id(data), goal_id: goal.id, amount: positive(payload.amount), reference_month: required(payload.reference_month, 'Informe o mês de referência.'), note: payload.note || null, created_at: new Date().toISOString() }; data.deposits.push(item); return copy(item) }) },
  async receivables() { const data = await state(); return data.receivables.map((item) => receivableView(data, item)) },
  async receivable(itemId) { const data = await state(); const item = find(data.receivables, itemId, 'Recebimento não encontrado.'); return { ...receivableView(data, item), payments: copy(data.receivablePayments.filter((entry) => entry.receivable_id === item.id).sort((a, b) => b.id - a.id)) } },
  async createReceivable(payload) { return change((data) => { const item = { id: id(data), name: required(payload.name?.trim(), 'Informe o nome.'), client: payload.client || null, total_amount: positive(payload.total_amount), service_type: required(payload.service_type, 'Informe o tipo de serviço.'), created_at: new Date().toISOString() }; data.receivables.push(item); return receivableView(data, item) }) },
  async updateReceivable(itemId, payload) { return change((data) => { const item = find(data.receivables, itemId, 'Recebimento não encontrado.'); Object.assign(item, { name: required(payload.name?.trim(), 'Informe o nome.'), client: payload.client || null, total_amount: positive(payload.total_amount), service_type: required(payload.service_type, 'Informe o tipo de serviço.') }); return receivableView(data, item) }) },
  async deleteReceivable(itemId) { return change((data) => { data.receivables = data.receivables.filter((item) => item.id !== Number(itemId)); data.receivablePayments = data.receivablePayments.filter((item) => item.receivable_id !== Number(itemId)); return null }) },
  async addReceivablePayment(receivableId, payload) { return change((data) => { const item = find(data.receivables, receivableId, 'Recebimento não encontrado.'); const amount = positive(payload.amount); if (amount > receivableView(data, item).pending_amount) throw new Error('O valor não pode ser maior que o saldo pendente.'); const payment = { id: id(data), receivable_id: item.id, amount, received_on: required(payload.received_on, 'Informe a data.'), note: payload.note || null }; data.receivablePayments.push(payment); createTransaction(data, { date: payment.received_on, type: 'income', amount, description: `Recebimento: ${item.name}` }); return copy(payment) }) },
  async recurringTransactions() { const data = await state(); return copy(data.recurring) },
  async createRecurringTransaction(payload) { return change((data) => { category(data, payload.category_id); const item = { id: id(data), ...copy(payload), amount: positive(payload.amount), category_id: Number(payload.category_id), is_active: true }; data.recurring.push(item); return copy(item) }) },
  async updateRecurringTransaction(itemId, payload) { return change((data) => { const item = find(data.recurring, itemId, 'Recorrência não encontrada.'); category(data, payload.category_id); Object.assign(item, copy(payload), { amount: positive(payload.amount), category_id: Number(payload.category_id) }); data.occurrences = data.occurrences.filter((entry) => entry.recurring_transaction_id !== item.id || entry.status === 'confirmed'); return copy(item) }) },
  async pauseRecurringTransaction(itemId) { return change((data) => { find(data.recurring, itemId, 'Recorrência não encontrada.').is_active = false; return null }) },
  async resumeRecurringTransaction(itemId) { return change((data) => { find(data.recurring, itemId, 'Recorrência não encontrada.').is_active = true; return null }) },
  async deleteRecurringTransaction(itemId) { return change((data) => { data.recurring = data.recurring.filter((item) => item.id !== Number(itemId)); data.occurrences = data.occurrences.filter((item) => item.recurring_transaction_id !== Number(itemId)); return null }) },
  async generateOccurrences(itemId) { return change((data) => { const recurring = find(data.recurring, itemId, 'Recorrência não encontrada.'); if (!recurring.is_active) return []; const existing = new Set(data.occurrences.filter((item) => item.recurring_transaction_id === recurring.id).map((item) => item.due_date)); const created = occurrenceDates(recurring).filter((date) => !existing.has(date)).map((due_date) => ({ id: id(data), recurring_transaction_id: recurring.id, due_date, status: 'pending', name: recurring.name, type: recurring.type, amount: recurring.amount, category_id: recurring.category_id })); data.occurrences.push(...created); return copy(created) }) },
  async occurrences(params = {}) { const data = await state(); return copy(data.occurrences.filter((item) => (!params.period || month(item.due_date) === params.period) && (!params.type || item.type === params.type) && (!params.status || item.status === params.status))) },
  async occurrenceSummary(period) { const data = await state(); const items = data.occurrences.filter((item) => month(item.due_date) === period); return { income_expected: items.filter((item) => item.type === 'income' && item.status === 'pending').reduce((sum, item) => sum + item.amount, 0), expense_expected: items.filter((item) => item.type === 'expense' && item.status === 'pending').reduce((sum, item) => sum + item.amount, 0), income_confirmed: items.filter((item) => item.type === 'income' && item.status === 'confirmed').reduce((sum, item) => sum + item.amount, 0), expense_confirmed: items.filter((item) => item.type === 'expense' && item.status === 'confirmed').reduce((sum, item) => sum + item.amount, 0) } },
  async confirmOccurrence(itemId) { return change((data) => { const item = find(data.occurrences, itemId, 'Ocorrência não encontrada.'); if (item.status === 'confirmed') return copy(item); item.status = 'confirmed'; item.transaction_id = createTransaction(data, { date: item.due_date > today() ? today() : item.due_date, type: item.type, amount: item.amount, category_id: item.category_id, description: item.name }).id; return copy(item) }) },
  async creditCards() { const data = await state(); return copy(data.cards) },
  async createCreditCard(payload) { return change((data) => { const item = { id: id(data), name: required(payload.name?.trim(), 'Informe o nome do cartão.'), brand: payload.brand || null, credit_limit: payload.credit_limit ? positive(payload.credit_limit) : null, closing_day: Number(payload.closing_day), due_day: Number(payload.due_day) }; data.cards.push(item); return copy(item) }) },
  async creditCard(itemId) { const data = await state(); const item = find(data.cards, itemId, 'Cartão não encontrado.'); return { ...copy(item), invoices: copy(data.invoices.filter((invoice) => invoice.credit_card_id === item.id)) } },
  async creditCardInvoice(itemId) { const data = await state(); const item = find(data.invoices, itemId, 'Fatura não encontrada.'); const purchases = data.purchases.filter((purchase) => purchase.invoice_id === item.id).map((purchase) => ({ ...copy(purchase), category_name: data.categories.find((categoryItem) => categoryItem.id === purchase.category_id)?.name || null })); const paid_amount = data.invoicePayments.filter((payment) => payment.invoice_id === item.id).reduce((sum, payment) => sum + payment.amount, 0); return { ...copy(item), purchases, paid_amount, pending_amount: Math.max(0, item.total_amount - paid_amount), payments: copy(data.invoicePayments.filter((payment) => payment.invoice_id === item.id)) } },
  async importCreditCardCsv(cardId, payload) { return change((data) => { find(data.cards, cardId, 'Cartão não encontrado.'); let invoice = data.invoices.find((item) => item.credit_card_id === Number(cardId) && item.reference_month === payload.reference_month); if (!invoice) { invoice = { id: id(data), credit_card_id: Number(cardId), reference_month: payload.reference_month, total_amount: 0, status: 'open' }; data.invoices.push(invoice) } const lines = payload.content.trim().split(/\r?\n/); const added = []; for (const line of lines.slice(1)) { const [date, title, amountValue] = line.split(','); const amount = Number(String(amountValue || '').replace(',', '.')); if (!date || !title || !Number.isFinite(amount) || /pagamento recebido/i.test(title)) continue; const purchase = { id: id(data), invoice_id: invoice.id, date, title, amount: Math.abs(amount), category_id: null }; data.purchases.push(purchase); invoice.total_amount += purchase.amount; added.push(purchase) } return copy(added) }) },
  async setCreditCardPurchaseCategory(itemId, categoryId) { return change((data) => { const item = find(data.purchases, itemId, 'Compra não encontrada.'); item.category_id = categoryId === null ? null : category(data, categoryId).id; return copy(item) }) },
  async deleteCreditCardInvoice(itemId) { return change((data) => { data.invoices = data.invoices.filter((item) => item.id !== Number(itemId)); data.purchases = data.purchases.filter((item) => item.invoice_id !== Number(itemId)); data.invoicePayments = data.invoicePayments.filter((item) => item.invoice_id !== Number(itemId)); return null }) },
  async addCreditCardInvoicePayment(itemId, payload) { return change((data) => { const invoice = find(data.invoices, itemId, 'Fatura não encontrada.'); const amount = positive(payload.amount); const payment = { id: id(data), invoice_id: invoice.id, amount, paid_on: payload.paid_on, paid_by_owner: Boolean(payload.paid_by_owner), payer_name: payload.payer_name || null, description: payload.description || null }; data.invoicePayments.push(payment); if (payment.paid_by_owner) createTransaction(data, { date: payment.paid_on, type: 'expense', amount, category_id: data.categories.find((item) => item.name === 'Outros').id, description: payment.description || `Pagamento de fatura ${invoice.reference_month}` }); return copy(payment) }) },
  async payCreditCardInvoice(itemId, payload) { const invoice = await this.creditCardInvoice(itemId); return this.addCreditCardInvoicePayment(itemId, { ...payload, amount: invoice.pending_amount }) },
  async saasClients() { const data = await state(); return copy(data.clients) },
  async createSaasClient(payload) { return change((data) => { const item = { id: id(data), ...copy(payload) }; data.clients.push(item); return copy(item) }) },
  async updateSaasClient(itemId, payload) { return change((data) => { const item = find(data.clients, itemId); Object.assign(item, copy(payload)); return copy(item) }) },
  async saasProducts() { const data = await state(); return copy(data.products) },
  async createSaasProduct(payload) { return change((data) => { const item = { id: id(data), ...copy(payload) }; data.products.push(item); return copy(item) }) },
  async updateSaasProduct(itemId, payload) { return change((data) => { const item = find(data.products, itemId); Object.assign(item, copy(payload)); return copy(item) }) },
  async saasPlans() { const data = await state(); return copy(data.plans) },
  async createSaasPlan(payload) { return change((data) => { find(data.products, payload.product_id, 'Produto não encontrado.'); const item = { id: id(data), ...copy(payload), default_amount: positive(payload.default_amount) }; data.plans.push(item); return copy(item) }) },
  async updateSaasPlan(itemId, payload) { return change((data) => { const item = find(data.plans, itemId); Object.assign(item, copy(payload), { default_amount: positive(payload.default_amount) }); return copy(item) }) },
  async saasSubscriptions() { const data = await state(); return data.subscriptions.map((item) => ({ ...copy(item), client_name: data.clients.find((client) => client.id === item.client_id)?.name || '', product_name: data.products.find((product) => product.id === item.product_id)?.name || '' })) },
  async createSaasSubscription(payload) { return change((data) => { find(data.clients, payload.client_id, 'Cliente não encontrado.'); find(data.products, payload.product_id, 'Produto não encontrado.'); const item = { id: id(data), ...copy(payload), amount: positive(payload.amount), status: 'active' }; data.subscriptions.push(item); return copy(item) }) },
  async updateSaasSubscription(itemId, payload) { return change((data) => { const item = find(data.subscriptions, itemId); Object.assign(item, copy(payload), { amount: positive(payload.amount) }); return copy(item) }) },
  async saasSubscription(itemId) { const data = await state(); const item = find(data.subscriptions, itemId); return { ...copy(item), client_name: data.clients.find((client) => client.id === item.client_id)?.name || '', product_name: data.products.find((product) => product.id === item.product_id)?.name || '', invoices: copy(data.saasInvoices.filter((invoice) => invoice.subscription_id === item.id)) } },
  async pauseSaasSubscription(itemId) { return change((data) => { find(data.subscriptions, itemId).status = 'paused'; return null }) },
  async resumeSaasSubscription(itemId) { return change((data) => { find(data.subscriptions, itemId).status = 'active'; return null }) },
  async cancelSaasSubscription(itemId, payload) { return change((data) => { const item = find(data.subscriptions, itemId); item.status = 'cancelled'; item.canceled_at = payload.canceled_at || today(); return null }) },
  async generateSaasInvoices() { return change((data) => { const created = []; for (const subscription of data.subscriptions.filter((item) => item.status === 'active')) { const due_date = `${month()}-${String(subscription.due_day).padStart(2, '0')}`; if (data.saasInvoices.some((item) => item.subscription_id === subscription.id && item.due_date === due_date)) continue; const invoice = { id: id(data), subscription_id: subscription.id, amount: subscription.amount, due_date, status: 'pending', paid_amount: 0 }; data.saasInvoices.push(invoice); created.push(invoice) } return copy(created) }) },
  async saasInvoices(params = {}) { const data = await state(); return data.saasInvoices.filter((item) => !params.period || month(item.due_date) === params.period).map((item) => ({ ...copy(item), client_name: data.clients.find((client) => client.id === data.subscriptions.find((subscription) => subscription.id === item.subscription_id)?.client_id)?.name || '', subscription_name: data.subscriptions.find((subscription) => subscription.id === item.subscription_id)?.name || '' })) },
  async addSaasPayment(itemId, payload) { return change((data) => { const invoice = find(data.saasInvoices, itemId, 'Cobrança não encontrada.'); const payment = { id: id(data), invoice_id: invoice.id, amount: positive(payload.amount), paid_at: payload.paid_at, payment_method: payload.payment_method, note: payload.note || null }; data.saasPayments.push(payment); invoice.paid_amount += payment.amount; invoice.status = invoice.paid_amount >= invoice.amount ? 'paid' : 'partial'; createTransaction(data, { date: payment.paid_at, type: 'income', amount: payment.amount, description: `Assinatura: ${data.subscriptions.find((item) => item.id === invoice.subscription_id)?.name || ''}` }); return copy(payment) }) },
  async deleteSaasPayment(itemId) { return change((data) => { const payment = find(data.saasPayments, itemId, 'Pagamento não encontrado.'); const invoice = find(data.saasInvoices, payment.invoice_id); invoice.paid_amount -= payment.amount; invoice.status = invoice.paid_amount ? 'partial' : 'pending'; data.saasPayments = data.saasPayments.filter((item) => item.id !== payment.id); return null }) },
  async saasDashboard(period) { const data = await state(); const invoices = await this.saasInvoices({ period }); return { mrr: data.subscriptions.filter((item) => item.status === 'active' && item.billing_cycle === 'monthly').reduce((sum, item) => sum + item.amount, 0), expected: invoices.reduce((sum, item) => sum + item.amount, 0), received: invoices.reduce((sum, item) => sum + item.paid_amount, 0), overdue: invoices.filter((item) => item.status !== 'paid' && item.due_date < today()).reduce((sum, item) => sum + (item.amount - item.paid_amount), 0), upcoming: invoices.filter((item) => item.status !== 'paid').slice(0, 5) } },
}
